### ISSUE TITLE
Collaborator is null within Subject constructor

### ISSUE THREAD

**Issue by AlexLuya** [marcingrzejszczak/spock-subjects-collaborators-extension#13]
After adding a constructor into SomeClass in ConstructorInjectionSpec like this:	

````java
class SomeClass {
		private SomeOtherClass someOtherClass
		private SomeOtherClass someOtherClassToBeInjected

		public SomeClass(){
			someOtherClassToBeInjected.someMethod()
		}
}
````
Blew exception got thrown out

````java
java.lang.NullPointerException: Cannot invoke method someMethod() on null object
	at com.vsi.idp.client.homepage.PropertiesInjectionSpec$SomeClass.<init>(PropertiesInjectionSpec.groovy:56)
	at com.blogspot.toomuchcoding.spock.subjcollabs.NonConstructorBasedInjector.instantiateSubjectAndSetOnSpecification(NonConstructorBasedInjector.groovy:26)
	at com.blogspot.toomuchcoding.spock.subjcollabs.PropertyInjector.tryToInject(PropertyInjector.groovy:16)
	at com.blogspot.toomuchcoding.spock.subjcollabs.SubjectsCollaboratorsInterceptor.tryToInjectCandidatesIntoSubject_closure2(SubjectsCollaboratorsInterceptor.groovy:74)
	at com.blogspot.toomuchcoding.spock.subjcollabs.SubjectsCollaboratorsInterceptor.tryToInjectCandidatesIntoSubject(SubjectsCollaboratorsInterceptor.groovy:74)
	at com.blogspot.toomuchcoding.spock.subjcollabs.SubjectsCollaboratorsInterceptor.intercept_closure1(SubjectsCollaboratorsInterceptor.groovy:69)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at com.blogspot.toomuchcoding.spock.subjcollabs.SubjectsCollaboratorsInterceptor.intercept(SubjectsCollaboratorsInterceptor.groovy:69)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
````

**Comment by marcingrzejszczak** [comment]
And that's very good! Cause you're violating basic principles of decent programming :)

You have a perfectly valid constructor that the extension is executing. But you haven't filled the field with any value thus it's Null. That's why you get NPE.

The order of injection resolution is as follows
- constructor (you have a valid constructor so this is chosen)
- setters
- fields

**Comment by AlexLuya** [comment]
any way to change injection order to 

-- fields(make sure it will be injected before constructor invoking)
- constructor

**Comment by marcingrzejszczak** [comment]
No, sorry - it's against any good practice of coding. Why not inject the fields via constructor?

```
class SomeClass {
        private SomeOtherClass someOtherClass
        private SomeOtherClass someOtherClassToBeInjected

        public SomeClass( SomeOtherClass someOtherClass,
        SomeOtherClass someOtherClassToBeInjected){
            someOtherClassToBeInjected.someMethod()
        }
}
```

It's really as simple as that....

**Comment by AlexLuya** [comment]
Thx.
